// M4P5C TEST-ONLY full-production-graph KAT for the exact secure History
// receive composition:
// raw BACKEND_A2D frame -> HistorySecureCrypto opaque open -> SecurityStore
// replay admission -> M4P5A RAM delivery.
//
// All KAT History/Security persistence is RAM-backed public test state. No
// secure History RF receive path is enabled by this probe.

#include "m4p5c_history_receipt_probe.h"

#include <string.h>

#include "device_identity.h"
#include "flash_backend.h"
#include "history_delivery_coordinator.h"
#include "history_incarnation_source.h"
#include "history_receipt_admission.h"
#include "history_receipt_receiver.h"
#include "history_secure_crypto.h"
#include "history_store.h"
#include "security_format.h"
#include "security_store.h"
#include "storage_config.h"
#include "tlp_position_packet.h"

namespace orun_tlp::m4p5c_test {
namespace {

constexpr uint64_t kDeviceId = UINT64_C(0x1122334455667788);
constexpr uint32_t kKeyEpoch = 0x01020304U;
constexpr uint64_t kIncarnation = UINT64_C(0xA1A2A3A4A5A6A7A8);

const uint8_t kCredentialId[security_format::kCredentialIdSize] = {
    0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,
    0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF};

const uint8_t kRoot[security_format::kKRootSize] = {
    0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,
    0x08,0x09,0x0A,0x0B,0x0C,0x0D,0x0E,0x0F,
    0x10,0x11,0x12,0x13,0x14,0x15,0x16,0x17,
    0x18,0x19,0x1A,0x1B,0x1C,0x1D,0x1E,0x1F};

// Independently regenerated by test_m4p5c_history_receipt_vector.py.
// One explicit History identity (1), A2D counter 1.
const uint8_t kReceiptFrame[56] = {
    0x02,0x03,0x01,0x02,0x00,0x0C,0x00,0x00,
    0x11,0x22,0x33,0x44,0x55,0x66,0x77,0x88,
    0x01,0x02,0x03,0x04,0x00,0x00,0x00,0x00,
    0x00,0x00,0x00,0x01,0xA1,0xA2,0xA3,0xA4,
    0xA5,0xA6,0xA7,0xA8,0x18,0x62,0xEE,0xA2,
    0x32,0x70,0x80,0x31,0x9F,0xEE,0x07,0x6B,
    0x24,0x78,0x24,0x4F,0x78,0xCA,0xF8,0x91};

template <size_t Pages>
class RamFlash final : public FlashBackend {
 public:
  static constexpr size_t kSize =
      Pages * static_cast<size_t>(storage_config::kPageSize);

  bool begin() override {
    if (!initialized_) {
      memset(bytes_, 0xFF, sizeof(bytes_));
      initialized_ = true;
    }
    return true;
  }

  bool read(uint32_t offset, void* data, size_t size) const override {
    if (data == nullptr || offset > sizeof(bytes_) ||
        size > sizeof(bytes_) - offset)
      return false;
    memcpy(data, bytes_ + offset, size);
    return true;
  }

  FlashOpResult program(uint32_t offset, const void* data,
                        size_t size) override {
    if (data == nullptr || size == 0 ||
        offset > sizeof(bytes_) || size > sizeof(bytes_) - offset)
      return FlashOpResult::kFailed;

    const auto* source = static_cast<const uint8_t*>(data);
    for (size_t i = 0; i < size; ++i) {
      if ((bytes_[offset + i] & source[i]) != source[i])
        return FlashOpResult::kFailed;
    }
    for (size_t i = 0; i < size; ++i)
      bytes_[offset + i] &= source[i];
    return FlashOpResult::kDone;
  }

  FlashOpResult erasePage(uint32_t page) override {
    if (page >= Pages) return FlashOpResult::kFailed;
    memset(bytes_ + static_cast<size_t>(page) * storage_config::kPageSize,
           0xFF, storage_config::kPageSize);
    return FlashOpResult::kDone;
  }

 private:
  bool initialized_ = false;
  uint8_t bytes_[kSize]{};
};

class FixedIncarnationSource final : public HistoryIncarnationSource {
 public:
  bool generate(uint64_t& incarnation) override {
    incarnation = kIncarnation;
    return true;
  }
};

RamFlash<storage_config::kPageCount> history_flash;
RamFlash<storage_config::kFutureSecurityRegionPages> security_flash;
FixedIncarnationSource incarnation_source;
HistoryStore history_store(history_flash, &incarnation_source);
SecurityStore security_store(security_flash, security_flash);
HistorySecureCrypto crypto(security_store);
HistoryDeliveryCoordinator delivery(history_store);
HistoryReceiptAdmissionCoordinator admission(security_store, delivery);
HistoryReceiptReceiver receiver(history_store, crypto, admission);

bool settleHistory() {
  for (uint32_t guard = 0; guard < 2000U && history_store.busy(); ++guard)
    history_store.poll();
  return !history_store.busy();
}

bool settleSecurity() {
  for (uint32_t guard = 0; guard < 3000U && security_store.busy(); ++guard)
    security_store.poll();
  return !security_store.busy();
}

bool prepareHistory() {
  if (!history_store.begin(kDeviceId) || !settleHistory())
    return false;

  if (!history_store.canAppend()) {
    (void)history_store.prepareAppend();
    if (!settleHistory())
      return false;
  }

  uint32_t sequence = 0;
  uint64_t identity = 0;
  if (!history_store.nextSequence(sequence, identity) ||
      sequence != 0U || identity != 1U)
    return false;

  tlp::PositionPacket position{};
  position.source_device_id = kDeviceId;
  position.sequence_number = sequence;
  position.gnss_utc_epoch_seconds = 0x11223344U;
  position.latitude_e7 = 410000000;
  position.longitude_e7 = 290000000;
  position.altitude_mm = 1234;
  position.hdop_x100 = 150;
  position.satellites = 8;
  position.flags = tlp::kPositionFlagValidFix |
                   tlp::kPositionFlagValidUtcTime |
                   tlp::kPositionFlag3dFix;

  uint8_t packet[tlp::kPositionPacketSize]{};
  if (!tlp::serializePositionPacket(position, packet, sizeof(packet)) ||
      !history_store.append(packet, identity) ||
      !settleHistory())
    return false;

  bool append_success = false;
  return history_store.takeAppendResult(append_success) && append_success &&
         history_store.ready() &&
         history_store.incarnation() == kIncarnation &&
         history_store.count() == 1U &&
         history_store.acknowledgedThrough() == 0U &&
         history_store.deliveredThrough() == 0U;
}

bool provisionPublicCredential() {
  if (!security_store.begin(DeviceIdentity::fromLegacyUint64(kDeviceId)) ||
      security_store.state() != SecurityState::kUnprovisioned)
    return false;

  uint8_t credential_id[security_format::kCredentialIdSize]{};
  uint8_t root[security_format::kKRootSize]{};
  memcpy(credential_id, kCredentialId, sizeof(credential_id));
  memcpy(root, kRoot, sizeof(root));

  if (!security_store.commitCredential(
          credential_id, kKeyEpoch, root) ||
      !settleSecurity())
    return false;

  bool commit_success = false;
  if (!security_store.takeCommitResult(commit_success) || !commit_success)
    return false;

  if (!settleSecurity())
    return false;

  return security_store.ready() &&
         security_store.state() == SecurityState::kProvisioned &&
         security_store.currentKeyEpoch() == kKeyEpoch;
}

}  // namespace

HistoryReceiptKatResult runHistoryReceiptKat() {
  HistoryReceiptKatResult result{};

  result.history_ready = prepareHistory();
  result.provision = provisionPublicCredential();
  if (!result.history_ready || !result.provision)
    return result;

  const auto started =
      receiver.submitBackendDurableFrame(kReceiptFrame, sizeof(kReceiptFrame));
  result.opaque_started =
      started == HistoryReceiptReceiver::SubmitResult::kStarted &&
      receiver.pending() && security_store.busy() &&
      history_store.acknowledgedThrough() == 0U;

  if (!result.opaque_started)
    return result;

  // The pending M4P5B owner must reject a second raw frame before another
  // crypto/open or SecurityStore replay-result owner can overtake it.
  result.busy_guard =
      receiver.submitBackendDurableFrame(kReceiptFrame,
                                         sizeof(kReceiptFrame)) ==
          HistoryReceiptReceiver::SubmitResult::kBusy &&
      receiver.pending();

  result.replay_wait =
      receiver.service() ==
          HistoryReceiptAdmissionCoordinator::ServiceResult::kWaitingReplay &&
      history_store.acknowledgedThrough() == 0U;

  if (!result.busy_guard || !result.replay_wait || !settleSecurity())
    return result;

  result.applied =
      receiver.service() ==
          HistoryReceiptAdmissionCoordinator::ServiceResult::kApplied &&
      !receiver.pending() &&
      history_store.acknowledgedThrough() == 1U &&
      history_store.deliveredThrough() == 0U;

  if (!result.applied)
    return result;

  uint8_t tampered[sizeof(kReceiptFrame)]{};
  memcpy(tampered, kReceiptFrame, sizeof(tampered));
  tampered[sizeof(tampered) - 1U] ^= 0x01U;

  result.tamper_rejected =
      receiver.submitBackendDurableFrame(tampered, sizeof(tampered)) ==
          HistoryReceiptReceiver::SubmitResult::kAuthRejected &&
      !receiver.pending() &&
      history_store.acknowledgedThrough() == 1U;

  // The original valid frame authenticates again but its already-consumed A2D
  // counter must be rejected by SecurityStore before any second History effect.
  const auto duplicate =
      receiver.submitBackendDurableFrame(kReceiptFrame, sizeof(kReceiptFrame));
  result.duplicate_rejected =
      duplicate == HistoryReceiptReceiver::SubmitResult::kStarted &&
      receiver.service() ==
          HistoryReceiptAdmissionCoordinator::ServiceResult::kReplayRejected &&
      !receiver.pending() &&
      history_store.acknowledgedThrough() == 1U &&
      history_store.deliveredThrough() == 0U;

  return result;
}

}  // namespace orun_tlp::m4p5c_test
