; ORUN TLP M0: RAK4630/RAK4631 Arduino firmware target.
[platformio]
default_envs = rak4630
boards_dir = rakwireless/boards

[env:rak4630]
platform = nordicnrf52
board = rak4630
framework = arduino
monitor_speed = 115200
build_src_filter = ${env.build_src_filter}+<../rakwireless/variants/rak4630>
build_flags =
    -I rakwireless/variants/rak4630
lib_deps =
    beegee-tokyo/SX126x-Arduino@2.0.32
